import { useEffect, useState } from 'react';
import type { PointerEvent as ReactPointerEvent, KeyboardEvent as ReactKeyboardEvent } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, CalendarDays, Check, ChevronRight, Compass, ExternalLink, Flag, Heart, Leaf, LockKeyhole, Moon, Mountain, Rocket, Settings2, ShieldCheck, Snowflake, Sparkles, Sun, Users, Volume2, VolumeX, Wrench, X } from 'lucide-react';
import { useMissionStore } from '../state/missionStore';
import { PARTS } from '../data/parts';
import { CANDIDATES } from '../data/crew';
import { SOURCES_DATA } from '../data/sources';
import { validateLaunchReadiness } from '../engine/validation';
import { sound } from '../audio/soundEngine';
import type { CrewRole, MissionPhase } from '../types/mission';
import { Assembly } from './Assembly';
import { Flight } from './Flight';
import { Avatar, CrewPortrait, PartArt, Planet } from './art';
import { CORE_SLOTS, SYSTEM_SLOTS, partLesson, partName } from './catalog';
import { Dialog, Guide } from './shared';
import './dark.css';

const state=useMissionStore.getState;
const phaseChapter:Record<MissionPhase,string>={welcome:'A LITTLE CURIOSITY. A BIG ADVENTURE.',destination:'01 · A Moon-sized dream',mission:'01 · A Moon-sized dream',site:'01 · A Moon-sized dream',assembly:'02 · Made by you',crew:'03 · Better together',readiness:'04 · Ready, set…',launchpad:'05 · Into the sky',ascent:'05 · Into the sky',orbit:'MISSION ONE · COMPLETE'};
export function StoryGame() {
 const phase=useMissionStore(s=>s.currentPhase);const audio=useMissionStore(s=>s.audioSettings);const comingSoon=useMissionStore(s=>s.comingSoon);
 const [theme,setTheme]=useState<'light'|'dark'>(()=>{try{return localStorage.getItem('moonbound_theme_v1')==='light'?'light':'dark';}catch{return 'dark';}});
 const [notesWidth,setNotesWidth]=useState(()=>{try{const saved=Number(localStorage.getItem('moonbound_notes_width_v1'));return saved>=240&&saved<=550?saved:285;}catch{return 285;}});
 const [notes,setNotes]=useState(false);const [inspected,setInspected]=useState<string|null>(null);const [settings,setSettings]=useState(false);const [restart,setRestart]=useState(false);
 useEffect(()=>{try{localStorage.setItem('moonbound_theme_v1',theme);}catch{} document.documentElement.style.colorScheme=theme; document.querySelector<HTMLMetaElement>('meta[name="theme-color"]')?.setAttribute('content',theme==='dark'?'#09051c':'#f8f5ed');},[theme]);
 useEffect(()=>{try{localStorage.setItem('moonbound_notes_width_v1',String(notesWidth));}catch{}},[notesWidth]);
 const startNotesResize=(e:ReactPointerEvent<HTMLDivElement>)=>{if(window.innerWidth<=800)return;e.preventDefault();const startX=e.clientX,startWidth=notesWidth;const maxWidth=Math.min(550,Math.floor(window.innerWidth*.48));const move=(event:PointerEvent)=>setNotesWidth(Math.max(240,Math.min(maxWidth,startWidth+startX-event.clientX)));const stop=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',stop);window.removeEventListener('pointercancel',stop);};window.addEventListener('pointermove',move);window.addEventListener('pointerup',stop);window.addEventListener('pointercancel',stop);};
 const adjustNotesWidth=(e:ReactKeyboardEvent<HTMLDivElement>)=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();setNotesWidth(w=>Math.max(240,Math.min(550,w+(e.key==='ArrowLeft'?16:-16))));}else if(e.key==='Home'){e.preventDefault();setNotesWidth(240);}else if(e.key==='End'){e.preventDefault();setNotesWidth(550);}};
 useEffect(()=>{sound.setMuted(audio.isMuted);if(audio.isMuted&&'speechSynthesis' in window)window.speechSynthesis.cancel();},[audio.isMuted]);
 useEffect(()=>{window.scrollTo(0,0);},[phase]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')setNotes(false);};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[]);
 const inspect=(id:string)=>{setInspected(id);state().selectPart(id);};
 return <div className={`game theme-${theme} ${audio.reducedMotion?'reduced-motion':''}`}>
  <a className="skip-link" href="#game-content">Skip to game</a>
  <header className="game-header"><button className="brand" onClick={()=>state().setPhase('welcome')} aria-label="Moonbound home"><span className="brand-mark"><Rocket size={22}/></span><span>moonbound</span></button><span className="chapter-marker">{phaseChapter[phase]}</span><nav aria-label="Game tools"><button className={`round-btn notes-toggle ${notes?'active':''}`} aria-label="Toggle field notes sidebar" aria-expanded={notes} aria-controls="field-notes" title="Field notes" onClick={()=>setNotes(n=>!n)}><BookOpen size={20}/><span>Field notes</span></button><button className="round-btn theme-toggle" aria-label={theme==='dark'?'Switch to light mode':'Switch to dark mode'} aria-pressed={theme==='dark'} title={theme==='dark'?'Light mode':'Dark mode'} onClick={()=>setTheme(t=>t==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={20}/>:<Moon size={20}/>}</button><button className="round-btn" aria-label="Open settings" onClick={()=>setSettings(true)}><Settings2 size={20}/></button></nav></header>
  <div className={`game-layout ${notes?'notes-open':''}`}><main id="game-content" tabIndex={-1}>
   {phase==='welcome'?<Welcome/>:phase==='destination'?<Destination/>:phase==='mission'?<Mission/>:phase==='site'?<Site/>:phase==='assembly'?<Assembly onInspect={inspect}/>:phase==='crew'?<CrewPlanner/>:phase==='readiness'?<ReadinessPlanner/>:<Flight/>}
  </main>{notes&&<aside className="field-notes" id="field-notes" aria-label="Field notes" style={{width:notesWidth,flexBasis:notesWidth}}><div className="notes-resizer" role="separator" aria-label="Resize field notes" aria-orientation="vertical" aria-valuemin={240} aria-valuemax={550} aria-valuenow={notesWidth} tabIndex={0} onPointerDown={startNotesResize} onKeyDown={adjustNotesWidth} onDoubleClick={()=>setNotesWidth(285)} title="Drag to resize · double-click to reset"/><div className="notes-heading"><span><BookOpen size={19}/> Field notes</span><button className="round-btn" onClick={()=>setNotes(false)} aria-label="Close field notes"><X size={19}/></button></div>{inspected&&PARTS[inspected]?<PartDetails id={inspected}/>:<><div className="notebook-cover"><Moon size={40}/><h2>A curious mind<br/>goes a long way.</h2><p>Tap a rocket part to peek inside its story.</p></div><p className="muted">These extra notes are here when you want them. Close this panel to keep playing.</p></>}<details className="sources"><summary>For curious explorers & grown-ups</summary><p>This is an Apollo-inspired learning game. Prices are authored game estimates, not supplier quotes. Flight events are simplified; the launch path is not a physics simulation.</p>{SOURCES_DATA.filter(s=>s.url).map(s=><a key={s.id} href={s.url} target="_blank" rel="noreferrer">{s.title}<ExternalLink size={13}/></a>)}</details></aside>}</div>
  {comingSoon.isOpen&&<Dialog title={comingSoon.title} onClose={()=>state().closeComingSoon()}><div className="coming-art"><Planet kind="moon"/><span className="coming-lock"><LockKeyhole size={26}/></span></div><span className="eyebrow">COMING SOON</span><p>{comingSoon.description}</p><button className="primary" onClick={()=>state().closeComingSoon()}>Back to my adventure<ArrowRight size={18}/></button></Dialog>}
  {settings&&<Dialog title="Make yourself at home" onClose={()=>setSettings(false)}><div className="settings-options"><button className="setting-row" onClick={()=>setTheme(t=>t==='dark'?'light':'dark')} aria-pressed={theme==='dark'}>{theme==='dark'?<Sun/>:<Moon/>}<span>Night mode<small>{theme==='dark'?'Deep violet space · on':'Deep violet space · off'}</small></span><b>{theme==='dark'?'ON':'OFF'}</b></button><button className="setting-row" onClick={()=>state().toggleMute()} aria-pressed={!audio.isMuted}>{audio.isMuted?<VolumeX/>:<Volume2/>}<span>Sound & read-aloud<small>{audio.isMuted?'Off · a quiet adventure':'On · tap the speaker beside a hint'}</small></span><b>{audio.isMuted?'OFF':'ON'}</b></button><button className="setting-row" onClick={()=>state().toggleReducedMotion()} aria-pressed={audio.reducedMotion}><Leaf/><span>Gentle motion<small>Less movement, same adventure</small></span><b>{audio.reducedMotion?'ON':'OFF'}</b></button><button className="setting-row" onClick={()=>{setSettings(false);setRestart(true);}}><Rocket/><span>Start a new adventure<small>Begin with a fresh, empty workshop</small></span><ChevronRight/></button></div><p className="mini muted">Progress saves on this device. Sound and read-aloud need browser support.</p></Dialog>}
  {restart&&<Dialog title="A fresh start?" onClose={()=>setRestart(false)}><p>This clears your current rocket and crew. Your new workshop will be empty.</p><div className="dialog-actions"><button className="soft-button" onClick={()=>setRestart(false)}>Keep my adventure</button><button className="primary" onClick={()=>{state().resetMission();setRestart(false);setInspected(null);}}>Start fresh<ArrowRight size={18}/></button></div></Dialog>}
 </div>;
}
function Welcome() {
 const count=useMissionStore(s=>Object.keys(s.installedParts).length);
 return <div className="welcome"><div className="welcome-copy"><span className="eyebrow"><span className="tiny-star">✦</span> MISSION 01 · THE MOON IS CALLING</span><h1>Small explorer.<br/><span>Giant adventure.</span></h1><p>A Moon-sized dream starts with you.<br/>Build a rocket. Make a crew. Touch the stars.</p><button className="primary big" onClick={()=>state().setPhase(count?'assembly':'destination')}>{count?'Continue adventure':'Let’s play'}<ArrowRight size={22}/></button><div className="hero-byline"><span className="mini-avatars"><Avatar/><Avatar variant={2}/></span><span>Your crew is waiting.<br/><strong>No space experience needed.</strong></span></div></div>
  <div className="welcome-art"><div className="art-orbit orbit-a"/><div className="art-orbit orbit-b"/><span className="deco-star star-one">✦</span><span className="deco-star star-two">✧</span><div className="hero-moon"><Planet/><span>See you soon!</span></div><div className="comic-photo"><img src="/story/crew-welcome.png" alt="Two smiling astronauts wave hello to their new mission captain"/><div className="photo-caption"><span>MEET YOUR CREW</span><strong>“We saved you a spot!”</strong></div></div><span className="mission-sticker"><Rocket size={29}/><b>LET’S MAKE<br/>SOMETHING BIG.</b></span><span className="orbit-doodle">✦</span></div>

 </div>;
}
function Destination(){return <div className="chapter"><div className="chapter-top"><div><p className="eyebrow">CHAPTER 01 · A MOON-SIZED DREAM</p><h1>Where will curiosity take us?</h1></div><span className="sketch-spark">✦</span></div><div className="destination-grid"><button className="destination-card moon-card" onClick={()=>{state().selectDestination('moon');state().setPhase('mission');}}><span className="label-tag">OUR FIRST ADVENTURE</span><Planet/><div className="destination-caption"><span><small>OUR CLOSEST SPACE NEIGHBOUR</small><strong>The Moon</strong></span><span className="circle-arrow"><ArrowRight/></span></div><span className="orbit-ring"/></button><button className="destination-card mars-card" onClick={()=>state().openComingSoon('A Martian adventure','Mars is coming soon. Our first crew is getting ready for the Moon.')}><span className="label-tag"><LockKeyhole size={14}/> COMING SOON</span><Planet kind="mars"/><div className="destination-caption"><span><small>A DREAM FOR ANOTHER DAY</small><strong>Mars</strong></span><span className="circle-arrow"><LockKeyhole/></span></div></button></div><div className="chapter-footer"><button className="text-btn" onClick={()=>state().setPhase('welcome')}><ArrowLeft size={16}/> Back</button><Guide text="Hi, I’m Mira! The Moon has a secret hiding near its south pole. Shall we go find out?"/></div></div>;}
function Mission(){return <div className="chapter"><div className="chapter-top"><div><p className="eyebrow">THE MYSTERY</p><h1>A secret in the shadows<span className="dot">.</span></h1></div></div><div className="mission-story"><div className="story-portrait-panel"><img src="/story/mission-control.png" alt="Mira and her engineer studying the Moon in mission control"/><span className="image-label">MIRA’S MISSION ROOM</span></div><div className="mission-brief"><span className="label-tag mint"><Snowflake size={15}/> THE ICE EXPLORERS</span><h2>Could ice help<br/>us live on the Moon?</h2><p>Some deep craters never see sunlight.<br/>They can hold clues to frozen water.</p><div className="visual-mission"><span><Snowflake/>Find ice clues</span><span><Users/>Take a crew</span><span><Rocket/>Launch from Earth</span></div><button className="primary" onClick={()=>{state().selectMission('lunar-ice-explorer');state().setPhase('site');}}>I’m in!<ArrowRight size={20}/></button><div className="other-missions"><button onClick={()=>state().openComingSoon('Moon rock detectives','The geology story is coming soon. Let’s prepare our Ice Explorers crew first.')}><Mountain size={17}/> Rock detectives<LockKeyhole size={13}/></button><button onClick={()=>state().openComingSoon('Ancient Moon volcanoes','This story is coming soon. Your ice adventure is ready now.')}><Sparkles size={17}/> Volcano explorers<LockKeyhole size={13}/></button></div></div></div><div className="chapter-footer"><button className="text-btn" onClick={()=>state().setPhase('destination')}><ArrowLeft size={16}/> Back</button><Guide text="First, we’ll build a rocket and launch into Earth orbit. Exploring the Moon itself comes in a later chapter."/></div></div>;}
function Site(){const site=useMissionStore(s=>s.selectedSite);return <div className="chapter"><div className="chapter-top"><div><p className="eyebrow">A LITTLE PLANNING BEFORE WE BUILD</p><h1>Pick our future Moon camp<span className="dot">.</span></h1></div><span className="label-tag">PLANNING ONLY</span></div><div className="site-scene"><Planet kind="earth"/><span className="site-sun"><Sun size={58}/></span><div className="moon-mountains rear"/><div className="moon-mountains front"/><div className="moon-ground"/><button className={`site-pin ridge ${site==='ridge'?'chosen':''}`} onClick={()=>state().selectSite('ridge')} aria-pressed={site==='ridge'}><span><Flag size={24}/></span><strong>Sunny ridge</strong><small>More light · ice farther away</small>{site==='ridge'&&<b><Check size={13}/> CAMP CHOSEN</b>}</button><button className={`site-pin crater ${site==='crater-rim'?'chosen':''}`} onClick={()=>state().selectSite('crater-rim')} aria-pressed={site==='crater-rim'}><span><Snowflake size={24}/></span><strong>Crater rim</strong><small>Closer ice · longer shadows</small>{site==='crater-rim'&&<b><Check size={13}/> CAMP CHOSEN</b>}</button><button className="shadow-pin" onClick={()=>state().openComingSoon('The deep-shadow challenge','This cold, dark camp needs a future chapter with different power and survival equipment.')}><LockKeyhole size={15}/> Deep shadow · soon</button><span className="site-label">AN IMAGINED SOUTH POLE CAMPSITE</span></div><div className="chapter-footer"><button className="text-btn" onClick={()=>state().setPhase('mission')}><ArrowLeft size={16}/> Back</button><Guide text={site==='ridge'?'A sunny ridge gives us more light. Our explorers would travel farther to look for ice.':'Closer ice is exciting! Long shadows make power trickier, so an extra battery could help later.'}/><button className="primary" onClick={()=>state().setPhase('assembly')}>To the workshop<ArrowRight size={19}/></button></div></div>;}
const roleNames:Record<CrewRole,string>={commander:'Pilot',scientist:'Scientist',engineer:'Engineer'};
const roles:CrewRole[]=['commander','scientist','engineer'];
const RoleIcons={commander:Compass,scientist:Snowflake,engineer:Wrench};
function CrewPlanner(){
 const assignments=useMissionStore(s=>s.crewAssignments);
 const duration=useMissionStore(s=>s.missionDurationDays);
 const [role,setRole]=useState<CrewRole>(()=>roles.find(r=>!assignments[r])||'commander');
 const selected=CANDIDATES.filter(c=>c.primaryRole===role||c.secondaryRole===role);
 const complete=roles.every(r=>assignments[r]);
 const crewCount=Object.values(assignments).filter(Boolean).length;
 const consumables=Math.round(crewCount*duration*7.4);
 return <div className="chapter"><div className="chapter-top"><div><p className="eyebrow">CHAPTER 03 · CREW & MISSION PLAN</p><h1>Big adventures need a team<span className="dot">.</span></h1></div><span className="label-tag"><Users size={16}/>{crewCount} / 3 ABOARD</span></div>
  <div className="crew-room">
   <section className="duration-planner" aria-labelledby="duration-title"><div className="duration-heading"><span className="duration-icon"><CalendarDays size={22}/></span><span><small>MOON MISSION DURATION</small><strong id="duration-title">{duration} days</strong></span><b>8 day minimum</b></div><input type="range" min="8" max="21" step="1" value={duration} onChange={e=>state().setMissionDurationDays(Number(e.target.value))} aria-label="Mission duration in days" aria-valuetext={`${duration} days`}/><div className="duration-scale"><span>8 days<small>Apollo 11 baseline</small></span><span>21 days<small>Orion independent limit</small></span></div><p><strong>{consumables.toLocaleString()} kg</strong> of food, potable water, oxygen, clothing and packing margin for the selected crew so far. Longer missions need more supplies; missions beyond 21 days need an additional habitat.</p></section>
   <div className="crew-seats">{roles.map(r=>{const id=assignments[r];const c=CANDIDATES.find(candidate=>candidate.id===id);const Icon=RoleIcons[r];return <button key={r} className={`crew-seat ${role===r?'active':''} ${c?'filled':''}`} onClick={()=>setRole(r)} aria-pressed={role===r}><span className="seat-role"><Icon size={18}/>{roleNames[r]}</span>{c?<CrewPortrait candidateId={c.id}/>:<div className="empty-helmet"><Users size={42}/><span>?</span></div>}<strong>{c?c.name.replace('Dr. ','').split(' ')[0]:'Your next teammate'}</strong><small>{r==='commander'?'Steers our spacecraft':r==='scientist'?'Investigates ice clues':'Keeps systems healthy'}</small>{c&&<span className="seat-check"><Check size={15}/></span>}</button>;})}</div>
   <div className="crew-pick"><div className="shelf-heading"><h2>Choose your {roleNames[role].toLowerCase()}</h2><span>FICTIONAL CREW</span></div><div className="candidate-row">{selected.map(c=><button key={c.id} className={`candidate ${assignments[role]===c.id?'selected':''}`} onClick={()=>{state().assignCrew(role,c.id);sound.playSnap();const next=roles.find(r=>!state().crewAssignments[r]);if(next)setRole(next);}}><CrewPortrait candidateId={c.id}/><span><strong>{c.name.replace('Dr. ','')}</strong><small>“{c.callsign}” · {roleNames[role]}</small></span>{assignments[role]===c.id?<Check size={19}/>:<span className="candidate-plus">+</span>}</button>)}</div></div>
  </div><div className="chapter-footer"><button className="text-btn" onClick={()=>state().setPhase('assembly')}><ArrowLeft size={16}/> Workshop</button><Guide person="leo" text={complete?`${duration} days means planning every meal, breath and battery. Your crew is ready!`:'Pick a pilot, a scientist and an engineer. Then choose how long the Moon mission will last.'}/><button className="primary" disabled={!complete} onClick={()=>state().setPhase('readiness')}>Ready together<ArrowRight size={19}/></button></div></div>;
}
function ReadinessPlanner(){
 const s=useMissionStore();
 const report=validateLaunchReadiness(s.selectedMission,s.selectedSite,s.installedParts,s.crewAssignments,s.missionDurationDays);
 const coreOk=CORE_SLOTS.every(x=>s.installedParts[x]);
 const systemsOk=SYSTEM_SLOTS.every(x=>s.installedParts[x]);
 const crewOk=roles.every(r=>s.crewAssignments[r]);
 const scienceOk=['neutron-spectrometer','nav-context-camera'].every(p=>Object.values(s.installedParts).includes(p));
 const checks=[{Icon:Rocket,title:'Flight systems',ok:coreOk,phase:'assembly'},{Icon:Heart,title:'Crew protected',ok:systemsOk,phase:'assembly'},{Icon:Users,title:'Three teammates',ok:crewOk,phase:'crew'},{Icon:Snowflake,title:'Moon kit',ok:scienceOk,phase:'assembly'},{Icon:ShieldCheck,title:'Weight & power',ok:!report.massSummary.isOverScienceMassLimit&&report.powerSummary.netPowerMarginWatts>=500,phase:'assembly'},{Icon:Flag,title:'Within budget',ok:!report.budgetSummary.isOverBudget,phase:'assembly'}];
 return <div className="chapter"><div className="chapter-top"><div><p className="eyebrow">CHAPTER 04 · A LITTLE CHECK, A BIG LEAP</p><h1>{report.isClearToLaunch?'Looking good, captain!':'Let’s get launch-ready.'}</h1></div><span className="label-tag"><CalendarDays size={15}/>{s.missionDurationDays} DAY PLAN</span></div><div className="readiness-room"><div className="ready-rocket ready-crew-panel"><span className="label-tag"><Sparkles size={15}/> YOUR FLIGHT CREW</span><div className="ready-crew-portraits">{roles.map(r=>{const c=CANDIDATES.find(candidate=>candidate.id===s.crewAssignments[r]);return <div className="ready-crew-member" key={r}>{c?<CrewPortrait candidateId={c.id}/>:<span className="empty-crew-slot"><Users size={30}/></span>}<strong>{c?c.name.replace('Dr. ','').split(' ')[0]:roleNames[r]}</strong><small>{roleNames[r]}</small></div>;})}</div><p>{report.massSummary.crewDailyConsumablesKg.toLocaleString()} kg consumables · {s.missionDurationDays} days</p></div><div className="ready-list"><p className="eyebrow">OUR LAUNCH PASSPORT</p><h2>Every explorer<br/>looks after their crew.</h2><div className="check-grid">{checks.map(({Icon,title,ok,phase})=><button key={title} className={`readiness-card ${ok?'ok':'missing'}`} onClick={()=>s.setPhase(phase as MissionPhase)}><Icon size={28}/><strong>{title}</strong><span>{ok?<><Check size={14}/> Ready</>:<>Let’s fix it <ArrowRight size={14}/></>}</span></button>)}</div>{report.blockers.length>0&&<p className="mini readiness-warning">{report.blockers[0].description}</p>}</div></div><div className="chapter-footer"><button className="text-btn" onClick={()=>s.setPhase('crew')}><ArrowLeft size={16}/> Crew</button><Guide person="kai" text={report.isClearToLaunch?'All green! Meet me at the launch pad. You’ll help our crew get ready for countdown.':'Tap an unfinished check. We’ll help you find what is missing or over the limit.'}/><button className="primary" disabled={!report.isClearToLaunch} onClick={()=>{if(s.prepareLaunch())s.setPhase('launchpad');}}>To the launch pad<Rocket size={18}/></button></div></div>;
}
function Crew(){const assignments=useMissionStore(s=>s.crewAssignments);const [role,setRole]=useState<CrewRole>(()=>roles.find(r=>!assignments[r])||'commander');const selected=CANDIDATES.filter(c=>c.primaryRole===role||c.secondaryRole===role);const complete=roles.every(r=>assignments[r]);return <div className="chapter"><div className="chapter-top"><div><p className="eyebrow">CHAPTER 03 · BETTER TOGETHER</p><h1>Big adventures need a team<span className="dot">.</span></h1></div><span className="label-tag"><Users size={16}/>{Object.values(assignments).filter(Boolean).length} / 3 ABOARD</span></div><div className="crew-room"><div className="crew-seats">{roles.map(r=>{const id=assignments[r];const c=CANDIDATES.find(c=>c.id===id);const Icon=RoleIcons[r];return <button key={r} className={`crew-seat ${role===r?'active':''} ${c?'filled':''}`} onClick={()=>setRole(r)} aria-pressed={role===r}><span className="seat-role"><Icon size={18}/>{roleNames[r]}</span>{c?<CrewPortrait candidateId={c.id}/>:<div className="empty-helmet"><Users size={42}/><span>?</span></div>}<strong>{c?c.name.replace('Dr. ','').split(' ')[0]:'Your next teammate'}</strong><small>{r==='commander'?'Steers our spacecraft':r==='scientist'?'Investigates ice clues':'Keeps systems healthy'}</small>{c&&<span className="seat-check"><Check size={15}/></span>}</button>;})}</div><div className="crew-pick"><div className="shelf-heading"><h2>Choose your {roleNames[role].toLowerCase()}</h2><span>FICTIONAL CREW</span></div><div className="candidate-row">{selected.map(c=><button key={c.id} className={`candidate ${assignments[role]===c.id?'selected':''}`} onClick={()=>{state().assignCrew(role,c.id);sound.playSnap();const next=roles.find(r=>!state().crewAssignments[r]);if(next)setRole(next);}}><CrewPortrait candidateId={c.id}/><span><strong>{c.name.replace('Dr. ','')}</strong><small>“{c.callsign}” · {roleNames[role]}</small></span>{assignments[role]===c.id?<Check size={19}/>:<span className="candidate-plus">+</span>}</button>)}</div></div></div><div className="chapter-footer"><button className="text-btn" onClick={()=>state().setPhase('assembly')}><ArrowLeft size={16}/> Workshop</button><Guide person="leo" text={complete?'Three different talents. One brilliant crew. Let’s get everyone ready to fly!':'Pick a pilot to steer, a scientist to discover, and an engineer to keep us safe.'}/><button className="primary" disabled={!complete} onClick={()=>state().setPhase('readiness')}>Ready together<ArrowRight size={19}/></button></div></div>;}
function Readiness(){const s=useMissionStore();const report=validateLaunchReadiness(s.selectedMission,s.selectedSite,s.installedParts,s.crewAssignments);const coreOk=CORE_SLOTS.every(x=>s.installedParts[x]);const systemsOk=SYSTEM_SLOTS.every(x=>s.installedParts[x]);const crewOk=roles.every(r=>s.crewAssignments[r]);const scienceOk=['neutron-spectrometer','nav-context-camera'].every(p=>Object.values(s.installedParts).includes(p));const checks=[{Icon:Rocket,title:'Rocket built',ok:coreOk,phase:'assembly'},{Icon:Heart,title:'Crew protected',ok:systemsOk,phase:'assembly'},{Icon:Users,title:'Three teammates',ok:crewOk,phase:'crew'},{Icon:Snowflake,title:'Discovery kit',ok:scienceOk,phase:'assembly'},{Icon:ShieldCheck,title:'Weight & power',ok:!report.massSummary.isOverScienceMassLimit&&report.powerSummary.netPowerMarginWatts>=500,phase:'assembly'},{Icon:Flag,title:'Within our budget',ok:!report.budgetSummary.isOverBudget,phase:'assembly'}];return <div className="chapter"><div className="chapter-top"><div><p className="eyebrow">CHAPTER 04 · A LITTLE CHECK, A BIG LEAP</p><h1>{report.isClearToLaunch?'Looking good, captain!':'Let’s get launch-ready.'}</h1></div></div><div className="readiness-room"><div className="ready-rocket ready-crew-panel"><span className="label-tag"><Sparkles size={15}/> YOUR FLIGHT CREW</span><div className="ready-crew-portraits">{roles.map(r=>{const c=CANDIDATES.find(candidate=>candidate.id===s.crewAssignments[r]);return <div className="ready-crew-member" key={r}>{c?<CrewPortrait candidateId={c.id}/>:<span className="empty-crew-slot"><Users size={30}/></span>}<strong>{c?c.name.replace('Dr. ','').split(' ')[0]:roleNames[r]}</strong><small>{roleNames[r]}</small></div>;})}</div><p>Three explorers. One Moon-sized mission.</p></div><div className="ready-list"><p className="eyebrow">OUR LAUNCH PASSPORT</p><h2>Every explorer<br/>looks after their crew.</h2><div className="check-grid">{checks.map(({Icon,title,ok,phase})=><button key={title} className={`readiness-card ${ok?'ok':'missing'}`} onClick={()=>s.setPhase(phase as MissionPhase)}><Icon size={28}/><strong>{title}</strong><span>{ok?<><Check size={14}/> Ready</>:<>Let’s fix it <ArrowRight size={14}/></>}</span></button>)}</div>{report.notes.length>0&&<p className="mini muted">Moon-camp tips are saved for later. Today’s job is a safe launch.</p>}</div></div><div className="chapter-footer"><button className="text-btn" onClick={()=>s.setPhase('crew')}><ArrowLeft size={16}/> Crew</button><Guide person="kai" text={report.isClearToLaunch?'All green! Meet me at the launch pad. You’ll help our crew get ready for countdown.':'Tap an unfinished check. We’ll help you find what’s missing.'}/><button className="primary" disabled={!report.isClearToLaunch} onClick={()=>{if(s.prepareLaunch())s.setPhase('launchpad');}}>To the launch pad<Rocket size={18}/></button></div></div>;}
function PartDetails({id}:{id:string}){const p=PARTS[id];return <div className="part-details"><div className="notes-art"><PartArt id={id}/></div><span className="eyebrow">A CLOSER LOOK</span><h2>{partName(id)}</h2><p className="kid-lesson">{partLesson[id]||p.educationalNote}</p><dl><div><dt>Real-world inspiration</dt><dd>{p.name}</dd></div><div><dt>Game price</dt><dd>{p.priceStatus==='includedInPackage'?'Included in the mission package':`$${(p.costDollars/1e6).toFixed(1)} million · estimate`}</dd></div><div><dt>Model mass</dt><dd>{p.massKg.toLocaleString()} kg</dd></div><div><dt>Power use</dt><dd>{p.powerWatts} W</dd></div></dl><details><summary>Tell me more</summary><p>{p.description}</p><p>{p.educationalNote}</p><small>Catalogue reference: {p.sourceCitation}. Values are adapted for the game.</small>{p.packageParentName&&<p>{p.packageParentName} · educational allocation.</p>}</details></div>;}
